import django.contrib.auth.views as AuthViews
from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic.edit import CreateView

from lxca import views

urlpatterns = patterns(
    '',
    # url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^$',
        views.LoginView.as_view(),
        name='home'),
    url(r'login/$',
        views.LoginView.as_view(),
        name='login'),
    url(r'logout/$',
        views.LogoutView.as_view(),
        name='logout'),
    url(r'^register/$',
        views.UserRegisterView.as_view(),
        name='user_register'),

    # catalog racks
    url(r'^attachment/catalog/rack/(?P<pk>\d+)/add/$',
        views.CatalogRack_attachment_add,
        name='catalog_rack_attachment_add'),
    url(r'^attachment/catalog/rack/(?P<pk>\d+)/delete/$',
        views.CatalogRack_attachment_delete,
        name='catalog_rack_attachment_delete'),
    url('^catalog/racks/$',
        views.CatalogRackList.as_view(),
        name='catalog_rack_list'),
    url(r'^catalog/rack/add/$',
        views.CatalogRackAdd.as_view(),
        name='catalog_rack_add'),
    url(r'^catalog/rack/(?P<pk>\d+)/delete/$',
        views.CatalogRackDelete.as_view(),
        name='catalog_rack_delete'),
    url(r'^catalog/rack/(?P<pk>\d+)/edit/$',
        views.CatalogRackEdit.as_view(),
        name='catalog_rack_edit'),
    url(r'^catalog/rack/(?P<pk>\d+)/$',
        views.CatalogRackDetail.as_view(),
        name='catalog_rack_detail'),

    # catalog switches
    url(r'^attachment/catalog/switch/(?P<pk>\d+)/add/$',
        views.CatalogSwitch_attachment_add,
        name='catalog_switch_attachment_add'),
    url(r'^attachment/catalog/switch/(?P<pk>\d+)/delete/$',
        views.CatalogSwitch_attachment_delete,
        name='catalog_switch_attachment_delete'),
    url('^catalog/switches/$',
        views.CatalogSwitchList.as_view(),
        name='catalog_switch_list'),
    url(r'^catalog/switch/add/$',
        views.CatalogSwitchAdd.as_view(),
        name='catalog_switch_add'),
    url(r'^catalog/switch/(?P<pk>\d+)/delete/$',
        views.CatalogSwitchDelete.as_view(),
        name='catalog_switch_delete'),
    url(r'^catalog/switch/(?P<pk>\d+)/edit/$',
        views.CatalogSwitchEdit.as_view(),
        name='catalog_switch_edit'),
    url(r'^catalog/switch/(?P<pk>\d+)/$',
        views.CatalogSwitchDetail.as_view(),
        name='catalog_switch_detail'),

    # catalog PDUs
    url(r'^attachment/catalog/pdu/(?P<pk>\d+)/add/$',
        views.CatalogPdu_attachment_add,
        name='catalog_pdu_attachment_add'),
    url(r'^attachment/catalog/pdu/(?P<pk>\d+)/delete/$',
        views.CatalogPdu_attachment_delete,
        name='catalog_pdu_attachment_delete'),
    url('^catalog/pdues/$',
        views.CatalogPduList.as_view(),
        name='catalog_pdu_list'),
    url(r'^catalog/pdu/add/$',
        views.CatalogPduAdd.as_view(),
        name='catalog_pdu_add'),
    url(r'^catalog/pdu/(?P<pk>\d+)/delete/$',
        views.CatalogPduDelete.as_view(),
        name='catalog_pdu_delete'),
    url(r'^catalog/pdu/(?P<pk>\d+)/edit/$',
        views.CatalogPduEdit.as_view(),
        name='catalog_pdu_edit'),
    url(r'^catalog/pdu/(?P<pk>\d+)/$',
        views.CatalogPduDetail.as_view(),
        name='catalog_pdu_detail'),

    # catalog servers
    url(r'^attachment/catalog/server/(?P<pk>\d+)/add/$',
        views.CatalogServer_attachment_add,
        name='catalog_server_attachment_add'),
    url(r'^attachment/catalog/server/(?P<pk>\d+)/delete/$',
        views.CatalogServer_attachment_delete,
        name='catalog_server_attachment_delete'),
    url('^catalog/servers/$',
        views.CatalogServerList.as_view(),
        name='catalog_server_list'),
    url(r'^catalog/server/add/$',
        views.CatalogServerAdd.as_view(),
        name='catalog_server_add'),
    url(r'^catalog/server/(?P<pk>\d+)/delete/$',
        views.CatalogServerDelete.as_view(),
        name='catalog_server_delete'),
    url(r'^catalog/server/(?P<pk>\d+)/edit/$',
        views.CatalogServerEdit.as_view(),
        name='catalog_server_edit'),
    url(r'^catalog/server/(?P<pk>\d+)/$',
        views.CatalogServerDetail.as_view(),
        name='catalog_server_detail'),

    # architect application
    url(r'^attachment/ref/application/(?P<pk>\d+)/add/$',
        views.ArchitectApplication_attachment_add,
        name='sa_application_attachment_add'),
    url(r'^attachment/ref/application/(?P<pk>\d+)/delete/$',
        views.ArchitectApplication_attachment_delete,
        name='sa_application_attachment_delete'),
    url('^ref/applications/$',
        views.ArchitectApplicationList.as_view(),
        name='sa_application_list'),
    url(r'^ref/application/add/$',
        views.ArchitectApplicationAdd.as_view(),
        name='sa_application_add'),
    url(r'^ref/application/(?P<pk>\d+)/delete/$',
        views.ArchitectApplicationDelete.as_view(),
        name='sa_application_delete'),
    url(r'^ref/application/(?P<pk>\d+)/edit/$',
        views.ArchitectApplicationEdit.as_view(),
        name='sa_application_edit'),
    url(r'^ref/application/(?P<pk>\d+)/$',
        views.ArchitectApplicationDetail.as_view(),
        name='sa_application_detail'),

    # architect solution
    url(r'^attachment/ref/solution/(?P<pk>\d+)/add/$',
        views.ArchitectSolution_attachment_add,
        name='sa_solution_attachment_add'),
    url(r'^attachment/ref/solution/(?P<pk>\d+)/delete/$',
        views.ArchitectSolution_attachment_delete,
        name='sa_solution_attachment_delete'),
    url('^ref/solutions/$',
        views.ArchitectSolutionList.as_view(),
        name='sa_solution_list'),
    url(r'^ref/solution/add/$',
        views.ArchitectSolutionAdd.as_view(),
        name='sa_solution_add'),
    url(r'^ref/solution/(?P<pk>\d+)/delete/$',
        views.ArchitectSolutionDelete.as_view(),
        name='sa_solution_delete'),
    url(r'^ref/solution/(?P<pk>\d+)/edit/$',
        views.ArchitectSolutionEdit.as_view(),
        name='sa_solution_edit'),
    url(r'^ref/solution/(?P<pk>\d+)/$',
        views.ArchitectSolutionDetail.as_view(),
        name='sa_solution_detail'),

    # order solution
    url('^order/solutions/$',
        views.OrderSolutionList.as_view(),
        name='order_solution_list'),
    url(r'^order/solution/add/$',
        views.OrderSolutionAdd.as_view(),
        name='order_solution_add'),
    url(r'^order/solution/(?P<pk>\d+)/delete/$',
        views.OrderSolutionDelete.as_view(),
        name='order_solution_delete'),
    url(r'^order/solution/(?P<pk>\d+)/edit/$',
        views.OrderSolutionEdit.as_view(),
        name='order_solution_edit'),
    url(r'^order/solution/(?P<pk>\d+)/$',
        views.OrderSolutionDetail.as_view(),
        name='order_solution_detail'),

    # order pdu
    url('^order/pdus/$',
        views.OrderPduList.as_view(),
        name='order_pdu_list'),
    url(r'^order/pdu/(?P<pk>\d+)/edit/$',
        views.OrderPduEdit.as_view(),
        name='order_pdu_edit'),

    # order switch
    url('^order/switches/$',
        views.OrderSwitchList.as_view(),
        name='order_switch_list'),
    url(r'^order/switch/(?P<pk>\d+)/edit/$',
        views.OrderSwitchEdit.as_view(),
        name='order_switch_edit'),

    # order server
    url('^order/servers/$',
        views.OrderServerList.as_view(),
        name='order_server_list'),
    url(r'^order/server/(?P<pk>\d+)/edit/$',
        views.OrderServerEdit.as_view(),
        name='order_server_edit'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
