# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import annoying.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
        ('lxca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(default=b'default name', max_length=64)),
                ('description', models.CharField(default=b'default description', max_length=64)),
                ('file', models.FileField(upload_to=b'%Y/%m/%d', verbose_name='Attachment')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(default=None, to=settings.AUTH_USER_MODEL, blank=True, help_text=b'', null=True, verbose_name='Creator')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='Note')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('size', models.CharField(default='1U', max_length=8, choices=[('1U', '1U'), ('2U', '2U')])),
                ('voltage', models.CharField(default='120-1', max_length=16, choices=[('120-1', '120V single phase'), ('208-1', '208V single phase'), ('120-3', '208V three phase'), ('400-3', '400V three phase')])),
                ('orientation', models.CharField(default='h', max_length=16, choices=[('h', 'Horizontal'), ('v', 'Vertical')])),
                ('form_factor', models.IntegerField(default=1, help_text='0=vertical mount, 1=1U, 2=2U, and so on', verbose_name='Form factor')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(default=b'', max_length=128)),
                ('tags', models.CharField(default=b'', max_length=32)),
                ('extra_vars', annoying.fields.JSONField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Is primary rack')),
                ('size', models.CharField(default='16U', max_length=8, choices=[('16U', '16U'), ('32U', '32U'), ('48U', '48U')])),
                ('width', models.FloatField(default=19, verbose_name=b'Rack width (inch)')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RackConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('rack', models.ForeignKey(to='lxca.Rack')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RaidAdapter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('size', models.CharField(default='1U', max_length=8, choices=[('1U', '1U'), ('2U', '2U')])),
                ('speed', models.CharField(default='PCIx1', max_length=32, verbose_name='PCI speed', choices=[(b'PCIx1', b'PCIx1'), (b'PCIx4', b'PCIx4'), (b'PCIx6', b'PCIx6')])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RaidAdapterConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('raid', models.ForeignKey(to='lxca.RaidAdapter')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('size', models.CharField(default='1U', max_length=8, choices=[('1U', '1U'), ('2U', '2U')])),
                ('cores', models.IntegerField(default=2)),
                ('mem', models.IntegerField(default=16, help_text='Memory size in GB')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('operating_system', models.CharField(default=b'Ubuntu xeniel', max_length=256, choices=[(b'win210svr', b'Windows Server 2010'), (b'esxi', b'ESXI server'), (b'Ubuntu xeniel', b'Ubuntu 16.04 Xeniel'), (b'Ubuntu trusty', b'Ubuntu 14.04 Trusty')])),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('server', models.ForeignKey(to='lxca.Server')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('internal_name', models.CharField(max_length=128, verbose_name='Internal solution name')),
                ('internal_major_version', models.IntegerField(default=0, verbose_name='Internal major version')),
                ('internal_minor_version', models.IntegerField(default=1, verbose_name='Internal minor version')),
                ('parent', models.ForeignKey(default=None, blank=True, to='lxca.Solution', null=True, verbose_name='Solution')),
                ('pdus', models.ManyToManyField(to='lxca.PDU')),
                ('racks', models.ManyToManyField(to='lxca.Rack')),
                ('servers', models.ManyToManyField(to='lxca.Server')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SolutionConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('solution', models.ForeignKey(to='lxca.Solution')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('size', models.CharField(default='1U', max_length=8, choices=[('1U', '1U'), ('2U', '2U')])),
                ('capacity', models.IntegerField(default=100)),
                ('capacity_unit', models.CharField(default='TB', max_length=8, choices=[('GB', 'GB'), ('TB', 'TB')])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('storage', models.ForeignKey(to='lxca.Storage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default='default name', max_length=128)),
                ('description', models.TextField(default=b'')),
                ('help_text', models.CharField(max_length=64, null=True, verbose_name='Help', blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(max_length=64, null=True, verbose_name='Serial number', blank=True)),
                ('is_debug', models.BooleanField(default=False)),
                ('uuid', models.CharField(default=b'uuid', max_length=32)),
                ('mtm', models.CharField(default=b'mtm', max_length=64)),
                ('firmware', models.CharField(default=b'firmware version', max_length=32)),
                ('size', models.CharField(default='1U', max_length=8, choices=[('1U', '1U'), ('2U', '2U')])),
                ('speed', models.CharField(default='1G', max_length=8, choices=[('1G', '1G'), ('10G', '10G')])),
                ('cooling_orientation', models.CharField(default='h', max_length=8, verbose_name='Cooling orientation', choices=[('h', 'Horizontal'), ('v', 'Vertical')])),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SwitchConfig',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bm_user', models.CharField(default=b'', max_length=64)),
                ('bm_password', models.CharField(default=b'', max_length=32)),
                ('bm_manager_url', models.URLField(default=b'')),
                ('imm_ip', models.GenericIPAddressField(null=True, blank=True)),
                ('imm_user', models.CharField(default=b'', max_length=64)),
                ('imm_password', models.CharField(default=b'', max_length=32)),
                ('firmware_update', models.CharField(default=b'', max_length=32)),
                ('config_pattern', models.CharField(default=b'', max_length=32)),
                ('playbooks', models.ManyToManyField(to='lxca.Playbook')),
                ('switch', models.ForeignKey(to='lxca.Switch')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tag', models.SlugField(default=b'', max_length=16, verbose_name='Tag')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='solution',
            name='storages',
            field=models.ManyToManyField(to='lxca.Storage'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='solution',
            name='switches',
            field=models.ManyToManyField(to='lxca.Switch'),
            preserve_default=True,
        ),
    ]
